fix crash on commit with deleted documents
The following sequence of events:

- start with an empty index
- add and then delete a document
- add at least 32 documents
- commit
- commit again

leads to a crash on the second commit operation

```
thread 'segment_updater0' panicked at 'index out of bounds: the len is 4 but the index is 4', src/fastfield/delete.rs:65:21
```

This happens because the `DeleteBitSet` used to track the deleted
documents in a segment is sized to be big enough to represent the
max doc id added, but the `is_deleted()` method can be used with
arbitrarily big indexes, leading to the access out of bounds.

The ultimate culprit is the `advance_deletes` function, which is
doing:
```
        for doc in 0u32..max_doc {
            if segment_reader.is_deleted(doc) {
                delete_bitset.insert(doc as usize);
            }
        }
```

`max_doc` here is bigger than the maximum index of the delete bitset
because we added enough documents.

This patch fixes the crash by making `DeleteBitSet::is_deleted(doc)`
method safe to call with any index.

Fixes gh-681